import { Project, Decision, Person, ConnectedSource } from './types'

export const mockPeople: Person[] = [
  {
    id: 'person-1',
    name: 'Alex Chen',
    email: 'alex@example.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alex',
    role: 'Engineering Lead',
  },
  {
    id: 'person-2',
    name: 'Sarah Johnson',
    email: 'sarah@example.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
    role: 'Product Manager',
  },
  {
    id: 'person-3',
    name: 'Mike Davis',
    email: 'mike@example.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mike',
    role: 'Backend Engineer',
  },
  {
    id: 'person-4',
    name: 'Emma Wilson',
    email: 'emma@example.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emma',
    role: 'Frontend Engineer',
  },
  {
    id: 'person-5',
    name: 'James Brown',
    email: 'james@example.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=James',
    role: 'DevOps Engineer',
  },
]

export const mockDecisions: Decision[] = [
  {
    id: 'decision-1',
    projectId: 'project-1',
    title: 'Switch to Supabase for Database',
    description:
      'Decided to migrate from Firebase to Supabase for better control over data and pricing. This allows us to have more flexibility in queries and custom functions.',
    author: mockPeople[0],
    status: 'active',
    category: 'Infrastructure',
    supersedes: ['decision-0'],
    supersededBy: [],
    affects: ['database-layer', 'auth-system', 'api-routes'],
    relatedCommits: ['abc123', 'def456'],
    relatedMessages: ['discord-msg-1', 'slack-msg-1'],
    timeline: {
      created: new Date('2024-01-15'),
      updated: new Date('2024-02-20'),
      implemented: new Date('2024-02-25'),
    },
    votes: 8,
    impact: 'high',
    tags: ['database', 'critical', 'infrastructure'],
  },
  {
    id: 'decision-2',
    projectId: 'project-1',
    title: 'Use React 19 with Hooks',
    description:
      'Standardize on React 19 with hooks for all new components. This ensures consistency and makes components more reusable.',
    author: mockPeople[3],
    status: 'active',
    category: 'Frontend',
    supersedes: [],
    supersededBy: [],
    affects: ['frontend-components', 'styling-system'],
    relatedCommits: ['ghi789', 'jkl012'],
    relatedMessages: ['discord-msg-2'],
    timeline: {
      created: new Date('2024-01-20'),
      updated: new Date('2024-01-22'),
    },
    votes: 10,
    impact: 'high',
    tags: ['frontend', 'react', 'standards'],
  },
  {
    id: 'decision-3',
    projectId: 'project-1',
    title: 'Adopt TypeScript Strictly',
    description: 'Enforce strict TypeScript configuration across the codebase to catch more errors at compile time.',
    author: mockPeople[0],
    status: 'active',
    category: 'Development',
    supersedes: [],
    supersededBy: [],
    affects: ['all-typescript-files', 'build-config'],
    relatedCommits: ['mno345'],
    relatedMessages: ['slack-msg-2', 'slack-msg-3'],
    timeline: {
      created: new Date('2024-02-01'),
      updated: new Date('2024-02-15'),
    },
    votes: 9,
    impact: 'high',
    tags: ['typescript', 'quality', 'standards'],
  },
  {
    id: 'decision-4',
    projectId: 'project-1',
    title: 'Use Tailwind CSS for Styling',
    description: 'Move away from CSS modules to Tailwind CSS for faster development and consistency.',
    author: mockPeople[3],
    status: 'reverted',
    category: 'Frontend',
    supersedes: [],
    supersededBy: ['decision-5'],
    affects: ['styling-system', 'components'],
    relatedCommits: ['pqr678'],
    relatedMessages: [],
    timeline: {
      created: new Date('2023-12-10'),
      updated: new Date('2024-01-05'),
    },
    votes: 6,
    impact: 'medium',
    tags: ['css', 'styling', 'reverted'],
  },
  {
    id: 'decision-5',
    projectId: 'project-1',
    title: 'Use shadcn/ui Component Library',
    description: 'Instead of custom Tailwind, use shadcn/ui for pre-built, accessible components with Tailwind integration.',
    author: mockPeople[3],
    status: 'active',
    category: 'Frontend',
    supersedes: ['decision-4'],
    supersededBy: [],
    affects: ['styling-system', 'components', 'ui-library'],
    relatedCommits: ['stu901', 'vwx234'],
    relatedMessages: ['discord-msg-3'],
    timeline: {
      created: new Date('2024-01-10'),
      updated: new Date('2024-01-25'),
      implemented: new Date('2024-02-01'),
    },
    votes: 11,
    impact: 'high',
    tags: ['ui', 'components', 'libraries'],
  },
  {
    id: 'decision-6',
    projectId: 'project-1',
    title: 'Implement Rate Limiting on API',
    description: 'Add rate limiting to prevent abuse and ensure fair usage of API endpoints.',
    author: mockPeople[2],
    status: 'active',
    category: 'Backend',
    supersedes: [],
    supersededBy: [],
    affects: ['api-middleware', 'authentication'],
    relatedCommits: ['yza567'],
    relatedMessages: ['slack-msg-4'],
    timeline: {
      created: new Date('2024-02-05'),
      updated: new Date('2024-02-18'),
    },
    votes: 7,
    impact: 'medium',
    tags: ['api', 'security', 'performance'],
  },
  {
    id: 'decision-7',
    projectId: 'project-1',
    title: 'Use Redis for Caching',
    description:
      'Implement Redis as our primary caching solution for sessions and frequently accessed data to improve performance.',
    author: mockPeople[4],
    status: 'active',
    category: 'Infrastructure',
    supersedes: [],
    supersededBy: [],
    affects: ['caching-system', 'session-management'],
    relatedCommits: ['bcd890'],
    relatedMessages: ['discord-msg-4', 'slack-msg-5'],
    timeline: {
      created: new Date('2024-02-10'),
      updated: new Date('2024-02-20'),
    },
    votes: 9,
    impact: 'high',
    tags: ['redis', 'caching', 'performance'],
  },
  {
    id: 'decision-8',
    projectId: 'project-1',
    title: 'Adopt Semantic Versioning',
    description: 'Follow semantic versioning (semver) for all releases to make version tracking clear and predictable.',
    author: mockPeople[0],
    status: 'active',
    category: 'Release',
    supersedes: [],
    supersededBy: [],
    affects: ['versioning', 'release-process'],
    relatedCommits: ['efg123'],
    relatedMessages: [],
    timeline: {
      created: new Date('2024-01-30'),
      updated: new Date('2024-02-05'),
    },
    votes: 8,
    impact: 'medium',
    tags: ['versioning', 'release', 'process'],
  },
]

export const mockProjects: Project[] = [
  {
    id: 'project-1',
    name: 'Hackathon Platform',
    description:
      'A comprehensive platform for organizing and managing hackathon events with team collaboration features.',
    slug: 'hackathon-platform',
    createdAt: new Date('2024-01-01'),
    members: mockPeople,
    connectedSources: [
      {
        id: 'source-1',
        type: 'discord',
        name: 'Hackathon Dev Server',
        connected: true,
        lastSync: new Date(),
        config: { serverId: '123456789' },
      },
      {
        id: 'source-2',
        type: 'github',
        name: 'hackathon-platform',
        connected: true,
        lastSync: new Date(),
        config: { repo: 'org/hackathon-platform' },
      },
      {
        id: 'source-3',
        type: 'slack',
        name: 'engineering-team',
        connected: false,
        config: { channelId: '' },
      },
    ],
    decisionCount: mockDecisions.length,
  },
  {
    id: 'project-2',
    name: 'Mobile App',
    description: 'Native mobile application for iOS and Android.',
    slug: 'mobile-app',
    createdAt: new Date('2024-02-01'),
    members: mockPeople.slice(0, 3),
    connectedSources: [
      {
        id: 'source-4',
        type: 'github',
        name: 'mobile-app',
        connected: true,
        lastSync: new Date(),
        config: { repo: 'org/mobile-app' },
      },
    ],
    decisionCount: 5,
  },
  {
    id: 'project-3',
    name: 'Data Analytics',
    description: 'Real-time analytics and reporting system for business intelligence.',
    slug: 'data-analytics',
    createdAt: new Date('2024-02-15'),
    members: mockPeople.slice(2, 5),
    connectedSources: [],
    decisionCount: 3,
  },
]

export const mockConnectedSources: ConnectedSource[] = [
  {
    id: 'source-1',
    type: 'discord',
    name: 'Hackathon Dev Server',
    connected: true,
    lastSync: new Date(),
    config: { serverId: '123456789', channelCount: '5' },
  },
  {
    id: 'source-2',
    type: 'github',
    name: 'hackathon-platform',
    connected: true,
    lastSync: new Date(),
    config: { repo: 'org/hackathon-platform', pullRequests: '32' },
  },
  {
    id: 'source-3',
    type: 'slack',
    name: 'engineering-team',
    connected: false,
    config: { channelId: '' },
  },
]
